"""Cut the cast stage's two webfonts (public/fonts/cast-*.woff2).

    python scripts/cast-fonts.py <fonts dir>

<fonts dir> holds the sources, which stay outside the repo:
  fontsource-shippori-mincho-b1-5.3.0/package/files/shippori-mincho-b1-japanese-400-normal.woff2
  extra/darts-font/DartsFont.ttf
(on the owner's machine: claude_kun/.local-tools/music/fonts — the same files the STARFALL MV used).

Both are SIL OFL 1.1 and both are renamed here (PR Cast Mincho, PR Cast Hand), as the MV did,
so a modified subset never goes out under the original name. Their licences sit beside the
woff2 files. The glyphs: kana, the punctuation and ASCII, plus every character in
scripts/cast-glyphs.txt (names, roles, ages, the stage's own words). A character missing from
the subset falls through to the next face in the stack (src/styles/cast-fonts.css, written here, lists
the exact unicode-range), so re-run this when the cast gains a kanji, but nothing breaks if not.
"""
import os
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'public', 'fonts')

BASE = set(range(0x20, 0x7F))  # ASCII
BASE |= set(range(0x3041, 0x3097)) | set(range(0x30A1, 0x30FB)) | {0x30FC, 0x30FD, 0x30FE}  # kana, ー
BASE |= {ord(c) for c in '、。「」『』（）・〜…！？：／　―‐→←◆◇☆★♪'}


def glyph_text() -> set[int]:
    with open(os.path.join(ROOT, 'scripts', 'cast-glyphs.txt'), encoding='utf-8') as f:
        text = ''.join(line for line in f if not line.startswith('#'))
    return {ord(c) for c in text if not c.isspace()}


def cut(src: str, dst: str, family: str, cps: set[int]) -> list[int]:
    font = TTFont(src)
    have = set(font.getBestCmap())
    keep = sorted(cps & have)
    opts = subset.Options()
    opts.flavor = 'woff2'
    opts.layout_features = ['*']
    opts.name_IDs = ['*']
    opts.notdef_outline = True
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=keep)
    sub.subset(font)
    for rec in font['name'].names:
        if rec.nameID in (1, 4, 16, 18, 21):
            rec.string = family
        elif rec.nameID == 6:
            rec.string = family.replace(' ', '')
    font.flavor = 'woff2'
    font.save(dst)
    return keep


def ranges(cps: list[int]) -> str:
    out, start, prev = [], None, None
    for c in cps:
        if start is None:
            start = prev = c
        elif c == prev + 1:
            prev = c
        else:
            out.append((start, prev))
            start = prev = c
    if start is not None:
        out.append((start, prev))
    return ','.join(f'U+{a:04X}' if a == b else f'U+{a:04X}-{b:04X}' for a, b in out)


def main() -> None:
    src_dir = sys.argv[1]
    cps = BASE | glyph_text()
    css = ['/* Generated by scripts/cast-fonts.py — do not edit. The cast stage\'s faces (SIL OFL 1.1,',
           '   renamed subsets; licences beside the woff2 files). unicode-range is exactly the subset, so a',
           '   missing glyph falls through to the next face in the stack. */']
    jobs = [
        ('fontsource-shippori-mincho-b1-5.3.0/package/files/shippori-mincho-b1-japanese-400-normal.woff2',
         'cast-mincho.woff2', 'PR Cast Mincho',
         'fontsource-shippori-mincho-b1-5.3.0/package/LICENSE', 'cast-mincho-OFL.txt',
         'PR Cast Mincho is a renamed subset of Shippori Mincho B1 (Regular).'),
        ('extra/darts-font/DartsFont.ttf', 'cast-hand.woff2', 'PR Cast Hand',
         'extra/darts-font/SIL_Open_Font_License.txt', 'cast-hand-OFL.txt',
         'PR Cast Hand is a renamed subset of ダーツフォント (Darts Font) by DAICHI.'),
    ]
    for src, dst, family, lic, lic_dst, credit in jobs:
        keep = cut(os.path.join(src_dir, src), os.path.join(OUT, dst), family, cps)
        with open(os.path.join(src_dir, lic), encoding='utf-8') as f:
            licence = f.read()
        with open(os.path.join(OUT, lic_dst), 'w', encoding='utf-8', newline='\n') as f:
            f.write(credit + '\n\n' + licence)
        size = os.path.getsize(os.path.join(OUT, dst))
        print(f'{dst}: {len(keep)} glyphs, {size // 1024} KB')
        css.append('@font-face {')
        css.append(f"  font-family: '{family}';")
        css.append(f"  src: url('/fonts/{dst}') format('woff2');")
        css.append('  font-display: swap;')
        css.append(f'  unicode-range: {ranges(keep)};')
        css.append('}')
    with open(os.path.join(ROOT, 'src', 'styles', 'cast-fonts.css'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(css) + '\n')


if __name__ == '__main__':
    main()
